import type { MotifSetId } from "./types";

export interface Motif {
  /** Short label that goes on the sticker card. */
  label: string;
  /** Single-emoji glyph used in the visual preview only. */
  glyph: string;
  /** Concrete subject hint that flows into the AI prompt. */
  subject: string;
}

/**
 * Each set carries 16 motifs so any sheet count (6/9/12/16) can pull from it.
 * Order matters — first 6 are the strongest of the set, so a 6-sheet still
 * reads as cohesive.
 */
export const MOTIF_SETS: Record<MotifSetId, Motif[]> = {
  "self-care-affirmations": [
    { label: "you got this", glyph: "✨", subject: "the words 'you got this' in elegant brush lettering" },
    { label: "soft day", glyph: "☁️", subject: "the words 'soft day' surrounded by tiny clouds" },
    { label: "rest is productive", glyph: "🌙", subject: "the words 'rest is productive' framed by a crescent moon" },
    { label: "be gentle", glyph: "🌸", subject: "the words 'be gentle' surrounded by cherry blossoms" },
    { label: "trust the timing", glyph: "⏳", subject: "the words 'trust the timing' beside a tiny hourglass" },
    { label: "you are enough", glyph: "💛", subject: "the words 'you are enough' inside a soft heart" },
    { label: "breathe", glyph: "🍃", subject: "the word 'breathe' beside two leaves" },
    { label: "slow morning", glyph: "☕", subject: "the words 'slow morning' beside a steaming mug" },
    { label: "tiny wins", glyph: "🌱", subject: "the words 'tiny wins' beside a sprout" },
    { label: "soft launch", glyph: "🌷", subject: "the words 'soft launch' beside a tulip" },
    { label: "main character", glyph: "🎀", subject: "the words 'main character' beside a ribbon bow" },
    { label: "stay grounded", glyph: "🌿", subject: "the words 'stay grounded' beside an herb sprig" },
    { label: "kind to yourself", glyph: "🤍", subject: "the words 'kind to yourself' inside a soft cloud" },
    { label: "no rush", glyph: "🕊", subject: "the words 'no rush' beside a flying dove" },
    { label: "soft yes", glyph: "✿", subject: "the words 'soft yes' beside a small flower" },
    { label: "let it be easy", glyph: "🪷", subject: "the words 'let it be easy' inside a lotus" },
  ],
  "habit-tracker": [
    { label: "water", glyph: "💧", subject: "a glass of water with a label that says 'water'" },
    { label: "sleep", glyph: "🌙", subject: "a crescent moon with the label 'sleep'" },
    { label: "move", glyph: "🏃", subject: "a tiny running figure with the label 'move'" },
    { label: "read", glyph: "📖", subject: "an open book with the label 'read'" },
    { label: "journal", glyph: "📓", subject: "a journal and pen with the label 'journal'" },
    { label: "stretch", glyph: "🧘", subject: "a tiny stretching figure with the label 'stretch'" },
    { label: "sun", glyph: "🌞", subject: "a smiling sun with the label 'sun'" },
    { label: "walk", glyph: "👟", subject: "a sneaker with the label 'walk'" },
    { label: "vitamins", glyph: "💊", subject: "two pills with the label 'vitamins'" },
    { label: "skincare", glyph: "🧴", subject: "a serum bottle with the label 'skincare'" },
    { label: "meditate", glyph: "☯", subject: "a yin-yang circle with the label 'meditate'" },
    { label: "tea", glyph: "🍵", subject: "a tea cup with the label 'tea'" },
    { label: "screen-free", glyph: "📵", subject: "a phone with a leaf with the label 'screen-free'" },
    { label: "create", glyph: "🎨", subject: "a paintbrush with the label 'create'" },
    { label: "rest", glyph: "💤", subject: "a soft pillow with the label 'rest'" },
    { label: "gratitude", glyph: "💝", subject: "a heart-shaped envelope with the label 'gratitude'" },
  ],
  "coffee-shop": [
    { label: "latte", glyph: "☕", subject: "a latte cup with foam art" },
    { label: "espresso", glyph: "🍫", subject: "a small espresso cup on a saucer" },
    { label: "matcha", glyph: "🍵", subject: "a matcha latte in a ceramic cup" },
    { label: "croissant", glyph: "🥐", subject: "a flaky butter croissant" },
    { label: "scone", glyph: "🥯", subject: "a vanilla scone with glaze" },
    { label: "iced coffee", glyph: "🧊", subject: "an iced coffee in a clear glass with a straw" },
    { label: "muffin", glyph: "🧁", subject: "a blueberry muffin in a paper liner" },
    { label: "hot cocoa", glyph: "🍫", subject: "a mug of hot cocoa with whipped cream" },
    { label: "tea pot", glyph: "🫖", subject: "a small porcelain teapot" },
    { label: "macaron", glyph: "🍪", subject: "three pastel macarons stacked" },
    { label: "cinnamon roll", glyph: "🌀", subject: "a glazed cinnamon roll" },
    { label: "donut", glyph: "🍩", subject: "a sprinkled donut" },
    { label: "bagel", glyph: "🥯", subject: "a bagel with cream cheese" },
    { label: "tea bag", glyph: "🌿", subject: "a tea bag with a paper tag" },
    { label: "cake slice", glyph: "🍰", subject: "a single slice of layered cake" },
    { label: "cafe stamp", glyph: "✉️", subject: "a vintage cafe loyalty stamp card" },
  ],
  "daily-moods": [
    { label: "happy", glyph: "😊", subject: "a smiley face with rosy cheeks" },
    { label: "sleepy", glyph: "😴", subject: "a sleepy face with a small Z above" },
    { label: "cozy", glyph: "🧣", subject: "a chunky knit scarf" },
    { label: "curious", glyph: "🔎", subject: "a small magnifying glass" },
    { label: "overwhelmed", glyph: "🌪", subject: "a tiny tornado of papers" },
    { label: "grateful", glyph: "🙏", subject: "two hands in a soft prayer" },
    { label: "dreamy", glyph: "💭", subject: "a thought cloud with stars inside" },
    { label: "soft", glyph: "🦢", subject: "a single feather floating" },
    { label: "fierce", glyph: "🔥", subject: "a small flame" },
    { label: "lazy", glyph: "🛌", subject: "a tiny bed with rumpled sheets" },
    { label: "social", glyph: "💬", subject: "two speech bubbles overlapping" },
    { label: "alone time", glyph: "🪞", subject: "a hand mirror" },
    { label: "playful", glyph: "🎈", subject: "a balloon on a string" },
    { label: "creative", glyph: "🌈", subject: "a small rainbow arc" },
    { label: "anxious", glyph: "💧", subject: "three water drops" },
    { label: "rested", glyph: "🌅", subject: "a sunrise over hills" },
  ],
  "cottage-florals": [
    { label: "lavender", glyph: "🪻", subject: "a sprig of lavender flowers" },
    { label: "daisy", glyph: "🌼", subject: "a single white daisy" },
    { label: "honeybee", glyph: "🐝", subject: "a small chubby honeybee" },
    { label: "mushroom", glyph: "🍄", subject: "a red-cap mushroom with white spots" },
    { label: "wildflower", glyph: "🌷", subject: "a small pink wildflower" },
    { label: "rose hip", glyph: "🌹", subject: "a rose hip on a stem" },
    { label: "fern", glyph: "🌿", subject: "a single fern frond" },
    { label: "strawberry", glyph: "🍓", subject: "a wild strawberry with leaves" },
    { label: "honey jar", glyph: "🍯", subject: "a small jar of honey with a wooden dipper" },
    { label: "bird", glyph: "🐦", subject: "a small songbird perched" },
    { label: "moth", glyph: "🦋", subject: "a soft cream-colored moth" },
    { label: "egg", glyph: "🥚", subject: "a speckled robin's egg" },
    { label: "bouquet", glyph: "💐", subject: "a small wildflower bouquet" },
    { label: "wheat", glyph: "🌾", subject: "a sheaf of wheat" },
    { label: "apple", glyph: "🍎", subject: "a small heirloom apple" },
    { label: "leaf", glyph: "🍃", subject: "a single curling leaf" },
  ],
  "stars-moons": [
    { label: "crescent", glyph: "🌙", subject: "a smiling crescent moon" },
    { label: "constellation", glyph: "✨", subject: "five connected stars forming a constellation" },
    { label: "shooting star", glyph: "🌠", subject: "a shooting star with a sparkle trail" },
    { label: "comet", glyph: "☄", subject: "a small comet with tail" },
    { label: "galaxy", glyph: "🌌", subject: "a swirling tiny galaxy" },
    { label: "sun", glyph: "🌞", subject: "a sunburst with a face" },
    { label: "saturn", glyph: "🪐", subject: "saturn with rings" },
    { label: "twinkle", glyph: "⭐", subject: "a four-point sparkle star" },
    { label: "eclipse", glyph: "🌑", subject: "a solar eclipse with corona" },
    { label: "milky way", glyph: "✨", subject: "a horizontal swoosh of stars" },
    { label: "wishing star", glyph: "⭐", subject: "a star with two hands clasped beneath" },
    { label: "north star", glyph: "🧭", subject: "a compass-rose star" },
    { label: "moon phases", glyph: "🌗", subject: "a row of three moon phases" },
    { label: "stardust", glyph: "✨", subject: "scattered tiny stars" },
    { label: "nebula", glyph: "🌌", subject: "a soft pastel nebula cloud" },
    { label: "lunar eclipse", glyph: "🌚", subject: "a deep red lunar eclipse" },
  ],
  weather: [
    { label: "rainy", glyph: "🌧", subject: "a cloud with three falling raindrops" },
    { label: "sunny", glyph: "☀️", subject: "a smiling sun with rays" },
    { label: "cloudy", glyph: "☁️", subject: "a fluffy single cloud" },
    { label: "snowy", glyph: "❄️", subject: "a single snowflake" },
    { label: "stormy", glyph: "⛈", subject: "a cloud with a lightning bolt" },
    { label: "foggy", glyph: "🌫", subject: "soft horizontal fog lines" },
    { label: "rainbow", glyph: "🌈", subject: "a small arched rainbow" },
    { label: "umbrella", glyph: "☂️", subject: "a cute umbrella" },
    { label: "puddle", glyph: "💧", subject: "a small puddle with a ripple" },
    { label: "windy", glyph: "🌬", subject: "a face blowing wind lines" },
    { label: "frosty", glyph: "🥶", subject: "a tiny snow-covered pine" },
    { label: "warm", glyph: "🔥", subject: "a steaming mug of cocoa" },
    { label: "breezy", glyph: "🍃", subject: "two leaves caught in wind" },
    { label: "drizzle", glyph: "💦", subject: "a cloud with a few drops" },
    { label: "moonrise", glyph: "🌜", subject: "a moon rising over hills" },
    { label: "first frost", glyph: "🍂", subject: "a frosted leaf" },
  ],
  "books-study": [
    { label: "open book", glyph: "📖", subject: "an open book with two pages curled" },
    { label: "stack", glyph: "📚", subject: "three stacked books in different colors" },
    { label: "highlighter", glyph: "🖍", subject: "a yellow highlighter" },
    { label: "sticky note", glyph: "📝", subject: "a sticky note with a corner curl" },
    { label: "pen", glyph: "🖊", subject: "a fountain pen" },
    { label: "tea", glyph: "🍵", subject: "a steaming mug" },
    { label: "reading nook", glyph: "🛋", subject: "a small armchair with a book" },
    { label: "lamp", glyph: "💡", subject: "a brass desk lamp glowing" },
    { label: "bookmark", glyph: "🔖", subject: "a tasseled bookmark" },
    { label: "glasses", glyph: "👓", subject: "round reading glasses" },
    { label: "candle", glyph: "🕯", subject: "a tall lit candle" },
    { label: "library card", glyph: "🪪", subject: "a vintage library card" },
    { label: "quill", glyph: "🪶", subject: "a quill with ink drop" },
    { label: "notebook", glyph: "📓", subject: "a closed leather notebook" },
    { label: "study", glyph: "📐", subject: "a triangle ruler and pencil crossed" },
    { label: "letter", glyph: "✉️", subject: "a sealed letter with wax stamp" },
  ],
};
